import Head from "next/head";
import Navbar from "../components/Navbar";
import AboutMe from "../components/AboutMe";
import Main from "../components/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eliezer Ruiz | Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <section>
        <Main />
      </section>
      <section>
        <AboutMe />
      </section>
    </div>
  );
}
